name: notification

on:
  pull_request:
    branches:
      - main
      - develop
      - 'feature/*'

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
      - name: Telegram notification
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ${{github.repository}} - a new ${{ github.event_name}} from [${{github.head_ref}}] to [${{github.base_ref}}] is created by ${{github.actor}}. Please review ${{github.event.pull_request.html_url}}.
